// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrNcXd5NSJPSPrJ5nZiVqXaAa1f83NZpM',
    appId: '1:415943093114:web:2607a33dbdb8f7e9e1c4c3',
    messagingSenderId: '415943093114',
    projectId: 'delypuno-ddd2d',
    authDomain: 'delypuno-ddd2d.firebaseapp.com',
    storageBucket: 'delypuno-ddd2d.firebasestorage.app',
    measurementId: 'G-22WXGG3STR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9F7oswSQGyQrUTgpI3GJYt84Ccxnu7QU',
    appId: '1:415943093114:android:9025c4ac8a4547a3e1c4c3',
    messagingSenderId: '415943093114',
    projectId: 'delypuno-ddd2d',
    storageBucket: 'delypuno-ddd2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuzzOHkwwqHWhyNc9QP0mZuek6zI4Io8Q',
    appId: '1:415943093114:ios:744fc51369b224e6e1c4c3',
    messagingSenderId: '415943093114',
    projectId: 'delypuno-ddd2d',
    storageBucket: 'delypuno-ddd2d.firebasestorage.app',
    iosClientId:
        '415943093114-hsdjqncbl5nne5tpl4k8ujv64pei87e4.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDelibery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuzzOHkwwqHWhyNc9QP0mZuek6zI4Io8Q',
    appId: '1:415943093114:ios:744fc51369b224e6e1c4c3',
    messagingSenderId: '415943093114',
    projectId: 'delypuno-ddd2d',
    storageBucket: 'delypuno-ddd2d.firebasestorage.app',
    iosClientId:
        '415943093114-hsdjqncbl5nne5tpl4k8ujv64pei87e4.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDelibery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrNcXd5NSJPSPrJ5nZiVqXaAa1f83NZpM',
    appId: '1:415943093114:web:f7f9ebe4aaf6d785e1c4c3',
    messagingSenderId: '415943093114',
    projectId: 'delypuno-ddd2d',
    authDomain: 'delypuno-ddd2d.firebaseapp.com',
    storageBucket: 'delypuno-ddd2d.firebasestorage.app',
    measurementId: 'G-YF25XLRSZ7',
  );
}
